[package]
name = "deps_dyn_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
deps_dynamic = { path = "./deps-dynamic" }

[profile.dev]
split-debuginfo = "unpacked"

[profile.dev.build-override]
opt-level = 3
